"""Markdown report generator."""


def generate_markdown_report(context: dict) -> str:
    findings = context.get("findings", [])
    stats = context.get("severity_counts", {})
    title = context.get("title", "NightOwl Pentest Report")
    scan_id = context.get("scan_id", "N/A")
    timestamp = context.get("timestamp", "N/A")

    lines = [
        f"# {title}",
        "",
        f"**Scan ID:** {scan_id}",
        f"**Generated:** {timestamp}",
        f"**Tool:** NightOwl v1.0.0",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| Critical | {stats.get('critical', 0)} |",
        f"| High | {stats.get('high', 0)} |",
        f"| Medium | {stats.get('medium', 0)} |",
        f"| Low | {stats.get('low', 0)} |",
        f"| Info | {stats.get('info', 0)} |",
        f"| **Total** | **{len(findings)}** |",
        "",
        "---",
        "",
        "## Findings Summary",
        "",
        "| # | Severity | Title | Target | CVSS | Module |",
        "|---|----------|-------|--------|------|--------|",
    ]

    for i, f in enumerate(findings, 1):
        sev = f.get("severity", "info").upper()
        lines.append(
            f"| {i} | {sev} | {f.get('title', '')} | {f.get('target', '')} | {f.get('cvss_score', 0)} | {f.get('module_name', '')} |"
        )

    lines.extend(["", "---", "", "## Detailed Findings", ""])

    for i, f in enumerate(findings, 1):
        sev = f.get("severity", "info").upper()
        lines.extend([
            f"### {i}. {f.get('title', '')}",
            "",
            f"- **Severity:** {sev}",
            f"- **CVSS Score:** {f.get('cvss_score', 0)}",
            f"- **Target:** {f.get('target', '')}",
            f"- **Module:** {f.get('module_name', '')}",
            "",
            "**Evidence:**",
            "```",
            f.get("evidence", "N/A"),
            "```",
            "",
            f"**Remediation:** {f.get('remediation', 'N/A')}",
            "",
            "---",
            "",
        ])

    lines.extend([
        "",
        "*Report generated by NightOwl v1.0.0*",
    ])

    return "\n".join(lines)
